# Generated by Django 3.0.5 on 2020-05-03 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0003_trades'),
    ]

    operations = [
        migrations.AddField(
            model_name='trades',
            name='time_frame',
            field=models.CharField(default='', max_length=30),
        ),
    ]
