# Generated by Django 3.0.5 on 2020-05-03 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0004_trades_time_frame'),
    ]

    operations = [
        migrations.AddField(
            model_name='trades',
            name='side',
            field=models.CharField(default='', max_length=30),
        ),
    ]
