# Generated by Django 3.0.5 on 2020-05-03 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0005_trades_side'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trades',
            name='open_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
