# Generated by Django 3.0.5 on 2020-05-03 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0006_auto_20200503_1918'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Trades',
        ),
    ]
