# Generated by Django 3.0.5 on 2020-05-13 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0008_trades'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BrokerAccounts',
        ),
    ]
