# Generated by Django 3.0.5 on 2020-05-16 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0009_delete_brokeraccounts'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomePageDefault',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_number', models.CharField(default='', max_length=30)),
            ],
        ),
    ]
