# Generated by Django 3.0.5 on 2020-05-18 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0010_homepagedefault'),
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ov_status', models.BooleanField()),
                ('ov_st_time', models.TimeField()),
                ('ov_en_time', models.TimeField()),
            ],
        ),
    ]
