# Generated by Django 3.0.5 on 2020-05-21 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0012_auto_20200521_1007'),
    ]

    operations = [
        migrations.AddField(
            model_name='trades',
            name='sl',
            field=models.FloatField(default=0.0),
        ),
    ]
