# Generated by Django 3.0.5 on 2021-01-06 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0013_trades_sl'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemMessages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('msg_type', models.CharField(default='', max_length=100)),
                ('msg', models.CharField(default='', max_length=200)),
                ('date', models.DateField(auto_now=True)),
            ],
        ),
    ]
