# Generated by Django 3.2.7 on 2021-09-02 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0016_auto_20210902_2151'),
    ]

    operations = [
        migrations.AddField(
            model_name='processinfo',
            name='is_done',
            field=models.BooleanField(default=False),
        ),
    ]
