# Generated by Django 3.2.7 on 2021-09-05 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0017_processinfo_is_done'),
    ]

    operations = [
        migrations.AddField(
            model_name='processinfo',
            name='pid',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='processinfo',
            name='type',
            field=models.CharField(default='', max_length=100),
        ),
    ]
