# Generated by Django 3.2.7 on 2021-09-07 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0018_auto_20210905_2304'),
    ]

    operations = [
        migrations.AddField(
            model_name='processinfo',
            name='msg',
            field=models.CharField(default='', max_length=100),
        ),
    ]
