# Generated by Django 3.2.7 on 2021-09-09 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0019_processinfo_msg'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='processinfo',
            name='pid',
        ),
        migrations.AddField(
            model_name='processinfo',
            name='broker_id',
            field=models.CharField(default='', max_length=100),
        ),
    ]
