# Generated by Django 3.2.7 on 2021-09-30 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0020_auto_20210909_1312'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemmessages',
            name='msg_sub_type',
            field=models.CharField(default='', max_length=100),
        ),
    ]
