# Generated by Django 3.2.7 on 2022-08-25 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0022_systemmessages_verified'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exceptions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exception_level', models.CharField(default='', max_length=100)),
                ('entity_code', models.CharField(default='', max_length=100)),
                ('exception_type', models.CharField(default='', max_length=100)),
                ('process', models.CharField(default='', max_length=100)),
                ('status', models.CharField(default='', max_length=100)),
                ('creation_date', models.DateTimeField()),
                ('security_id', models.CharField(default='', max_length=100)),
            ],
        ),
    ]
