# Generated by Django 3.2.7 on 2022-08-25 12:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0023_exceptions'),
    ]

    operations = [
        migrations.AddField(
            model_name='exceptions',
            name='calculation_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
