# Generated by Django 5.1.2 on 2025-03-20 15:27

import mysite.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0029_userprofile_failed_attempts_userprofile_locked_until'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=mysite.models.user_profile_image_path),
        ),
    ]
