# Generated by Django 3.0.5 on 2020-05-22 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risk', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RobotRisk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('robot', models.CharField(default='', max_length=50)),
                ('p_level', models.IntegerField(default=0)),
                ('in_exp', models.FloatField(default=0.0)),
                ('sl_policy', models.CharField(default='', max_length=20)),
            ],
        ),
    ]
