# Generated by Django 3.0.5 on 2020-05-22 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risk', '0002_robotrisk'),
    ]

    operations = [
        migrations.AddField(
            model_name='robotrisk',
            name='m_dd',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='robotrisk',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
    ]
