# Generated by Django 3.0.5 on 2021-01-06 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risk', '0004_auto_20210106_1218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='robotrisk',
            name='robot',
            field=models.CharField(default='', max_length=50, unique=True),
        ),
    ]
