# Generated by Django 3.0.5 on 2021-01-09 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risk', '0005_auto_20210106_1412'),
    ]

    operations = [
        migrations.AddField(
            model_name='robotrisk',
            name='daily_trade_limit',
            field=models.FloatField(default=0.0),
        ),
    ]
