# Generated by Django 3.0.5 on 2021-02-04 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risk', '0006_robotrisk_daily_trade_limit'),
    ]

    operations = [
        migrations.AddField(
            model_name='robotrisk',
            name='risk_per_trade',
            field=models.FloatField(default=0.0),
        ),
    ]
