# Generated by Django 3.0.5 on 2021-02-04 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risk', '0007_robotrisk_risk_per_trade'),
    ]

    operations = [
        migrations.AddField(
            model_name='robotrisk',
            name='pyramiding_level',
            field=models.FloatField(default=0.0),
        ),
    ]
