# Generated by Django 3.0.5 on 2021-02-10 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risk', '0008_robotrisk_pyramiding_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='robotrisk',
            name='quantity',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='robotrisk',
            name='quantity_type',
            field=models.CharField(default='Stop Based', max_length=50),
        ),
    ]
