# Generated by Django 3.2.7 on 2021-09-15 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risk', '0009_auto_20210210_2039'),
    ]

    operations = [
        migrations.AddField(
            model_name='robotrisk',
            name='sl',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='robotrisk',
            name='win_exp',
            field=models.FloatField(default=0.0),
        ),
    ]
