# Generated by Django 3.2.15 on 2022-09-14 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PortfolioProcessStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('portfolio_code', models.CharField(default='', max_length=30)),
                ('cash_holding', models.CharField(default='', max_length=30)),
                ('position', models.CharField(default='', max_length=30)),
                ('portfolio_holding', models.CharField(default='', max_length=30)),
            ],
        ),
    ]
