# Generated by Django 5.1.2 on 2025-05-23 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculations', '0002_processaudit_processexception'),
    ]

    operations = [
        migrations.AddField(
            model_name='processexception',
            name='process_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
