# Generated by Django 3.0.5 on 2021-01-10 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20210110_1017'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountBalance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_number', models.CharField(default='', max_length=50)),
                ('allocated', models.FloatField(default=0.0)),
                ('not_allocated', models.FloatField(default=0.0)),
                ('currency', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='AccountCashFlow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_number', models.CharField(default='', max_length=50)),
                ('cash_flow', models.FloatField(default=0.0)),
                ('currency', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='brokeraccounts',
            name='currency',
            field=models.CharField(default='', max_length=100),
        ),
    ]
