# Generated by Django 3.0.5 on 2021-01-10 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20210110_1136'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountcashflow',
            name='date',
            field=models.DateField(auto_now=True),
        ),
    ]
