# Generated by Django 4.1.5 on 2023-03-16 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_brokers'),
    ]

    operations = [
        migrations.AddField(
            model_name='brokeraccounts',
            name='account_name',
            field=models.CharField(default='', max_length=30),
        ),
    ]
