# Generated by Django 4.1.5 on 2023-03-16 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_brokeraccounts_account_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='brokeraccounts',
            name='owner',
            field=models.CharField(default='', max_length=30),
        ),
    ]
