# Generated by Django 4.1.5 on 2023-03-16 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_brokeraccounts_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brokeraccounts',
            name='account_number',
            field=models.CharField(default='', max_length=50),
        ),
    ]
