# Generated by Django 5.1.2 on 2025-03-04 14:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_brokeraccounts_margin_account_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.DeleteModel(
            name='AccountBalance',
        ),
        migrations.DeleteModel(
            name='AccountCashFlow',
        ),
        migrations.AddField(
            model_name='brokeraccounts',
            name='user',
            field=models.ForeignKey(db_column='user', default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
