# Generated by Django 5.1.2 on 2025-03-05 10:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_alter_brokeraccounts_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='brokers',
            name='api_support',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='brokers',
            name='type',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='brokers',
            name='user',
            field=models.ForeignKey(blank=True, db_column='user', default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='brokers',
            name='broker',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='brokers',
            name='broker_code',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddConstraint(
            model_name='brokers',
            constraint=models.UniqueConstraint(condition=models.Q(('api_support', True)), fields=('broker_code',), name='unique_broker_code_when_api_support_true'),
        ),
    ]
