# Generated by Django 5.1.2 on 2025-03-05 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_brokers_api_support_brokers_type_brokers_user_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='brokers',
            name='unique_broker_code_when_api_support_true',
        ),
    ]
