# Generated by Django 5.1.2 on 2025-04-28 19:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_remove_brokers_unique_broker_code_when_api_support_true'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='brokeraccounts',
            name='account_type',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.CreateModel(
            name='BrokerCredentials',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_token', models.CharField(default='', max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('password', models.CharField(blank=True, max_length=128, null=True)),
                ('broker', models.ForeignKey(blank=True, db_column='broker', default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.brokers')),
                ('user', models.ForeignKey(blank=True, db_column='user', default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
