# Generated by Django 5.1.2 on 2025-04-29 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_brokeraccounts_account_type_brokercredentials'),
    ]

    operations = [
        migrations.AddField(
            model_name='brokercredentials',
            name='environment',
            field=models.CharField(default='', max_length=100),
        ),
    ]
