# Generated by Django 5.1.2 on 2025-04-29 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_brokercredentials_environment'),
    ]

    operations = [
        migrations.AddField(
            model_name='brokercredentials',
            name='expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
