# Generated by Django 5.1.2 on 2025-04-29 13:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_brokercredentials_expiry_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='brokeraccounts',
            name='broker',
            field=models.ForeignKey(blank=True, db_column='broker', default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.brokers'),
        ),
    ]
