# Generated by Django 3.0.5 on 2020-04-23 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Robots',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('strategy', models.CharField(default='', max_length=50)),
                ('security', models.CharField(default='', max_length=50)),
                ('broker', models.CharField(default='', max_length=50)),
                ('status', models.CharField(default='', max_length=50)),
                ('pyramiding_level', models.FloatField(default=0.0)),
                ('in_exp', models.FloatField(default=0.0)),
            ],
        ),
    ]
