# Generated by Django 3.0.5 on 2020-04-26 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('robots', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='robots',
            name='env',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='robots',
            name='quantity',
            field=models.FloatField(default=0.0),
        ),
    ]
