# Generated by Django 3.0.5 on 2020-04-29 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('robots', '0002_auto_20200426_1023'),
    ]

    operations = [
        migrations.AddField(
            model_name='robots',
            name='time_frame',
            field=models.CharField(default='', max_length=50),
        ),
    ]
