# Generated by Django 3.0.5 on 2020-04-29 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('robots', '0003_robots_time_frame'),
    ]

    operations = [
        migrations.AddField(
            model_name='robots',
            name='account_number',
            field=models.CharField(default='', max_length=50),
        ),
    ]
