# Generated by Django 3.0.5 on 2020-05-02 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('robots', '0004_robots_account_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='robots',
            name='sl_policy',
            field=models.CharField(default='', max_length=50),
        ),
    ]
