# Generated by Django 3.0.5 on 2020-05-15 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('robots', '0005_robots_sl_policy'),
    ]

    operations = [
        migrations.AddField(
            model_name='robots',
            name='prec',
            field=models.IntegerField(default=1),
        ),
    ]
