# Generated by Django 3.0.5 on 2020-10-06 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('robots', '0006_robots_prec'),
    ]

    operations = [
        migrations.AlterField(
            model_name='robots',
            name='name',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
