# Generated by Django 3.0.5 on 2020-10-06 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('robots', '0007_auto_20201006_1700'),
    ]

    operations = [
        migrations.CreateModel(
            name='Balance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('robot_name', models.CharField(max_length=20)),
                ('daily_pnl', models.FloatField(default=0.0)),
                ('daily_cash_flow', models.FloatField(default=0.0)),
                ('balance', models.FloatField(default=0.0)),
                ('date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='CashFlow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('robot_name', models.CharField(max_length=20)),
                ('cash_flow', models.FloatField(default=0.0)),
                ('date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
