# Generated by Django 3.0.5 on 2020-10-14 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('robots', '0009_auto_20201013_2347'),
    ]

    operations = [
        migrations.CreateModel(
            name='RobotTrades',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('security', models.CharField(default='', max_length=30)),
                ('robot', models.CharField(default='', max_length=30)),
                ('quantity', models.FloatField(default=0.0)),
                ('strategy', models.CharField(default='', max_length=30)),
                ('status', models.CharField(default='', max_length=30)),
                ('pnl', models.FloatField(default=0.0)),
                ('open_price', models.FloatField(default=0.0)),
                ('close_price', models.FloatField(default=0.0)),
                ('open_time', models.DateTimeField(auto_now_add=True)),
                ('close_time', models.DateTimeField(auto_now=True)),
                ('time_frame', models.CharField(default='', max_length=30)),
                ('side', models.CharField(default='', max_length=30)),
                ('broker_id', models.IntegerField(default=0)),
                ('broker', models.CharField(default='', max_length=30)),
                ('sl', models.FloatField(default=0.0)),
            ],
        ),
    ]
