# Generated by Django 3.0.5 on 2020-10-15 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('robots', '0010_robottrades'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='robottrades',
            name='strategy',
        ),
        migrations.RemoveField(
            model_name='robottrades',
            name='time_frame',
        ),
        migrations.AlterField(
            model_name='robottrades',
            name='close_time',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='robottrades',
            name='open_time',
            field=models.DateField(auto_now_add=True),
        ),
    ]
