# Generated by Django 3.0.5 on 2020-10-25 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('robots', '0012_auto_20201025_1813'),
    ]

    operations = [
        migrations.AlterField(
            model_name='balance',
            name='date',
            field=models.DateField(auto_now=True),
        ),
    ]
