# Generated by Django 3.0.5 on 2020-10-25 18:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('robots', '0013_auto_20201025_1913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='balance',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
