# Generated by Django 3.0.5 on 2020-10-25 19:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('robots', '0015_auto_20201025_1930'),
    ]

    operations = [
        migrations.AddField(
            model_name='robots',
            name='inception_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
