# Generated by Django 3.0.5 on 2021-07-06 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('robots', '0016_robots_inception_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='robots',
            old_name='sl_policy',
            new_name='currency',
        ),
        migrations.RemoveField(
            model_name='robots',
            name='in_exp',
        ),
        migrations.RemoveField(
            model_name='robots',
            name='prec',
        ),
        migrations.RemoveField(
            model_name='robots',
            name='pyramiding_level',
        ),
        migrations.RemoveField(
            model_name='robots',
            name='quantity',
        ),
    ]
