# Generated by Django 3.2.7 on 2021-09-29 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('robots', '0017_auto_20210706_2136'),
    ]

    operations = [
        migrations.AddField(
            model_name='robots',
            name='strategy_params',
            field=models.JSONField(default={}),
            preserve_default=False,
        ),
    ]
