# Generated by Django 3.2.15 on 2022-09-20 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('robots', '0019_auto_20220920_1852'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='robots',
            name='strategy_params',
        ),
    ]
