# Generated by Django 3.2.15 on 2022-09-21 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('robots', '0020_remove_robots_strategy_params'),
    ]

    operations = [
        migrations.AlterField(
            model_name='robots',
            name='name',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
