# Generated by Django 3.2.15 on 2022-09-22 12:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('robots', '0021_alter_robots_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlyReturns',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('robot_code', models.CharField(default='', max_length=30)),
                ('ret', models.FloatField(default=0.0)),
                ('date', models.DateField(default=datetime.date.today)),
            ],
        ),
    ]
