# Generated by Django 3.2.15 on 2022-09-26 16:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('robots', '0022_auto_20220923_1204'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlyReturns',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('robot_id', models.IntegerField(default=0)),
                ('ret', models.FloatField(default=0.0)),
                ('date', models.DateField(default=datetime.date.today)),
            ],
        ),
    ]
