# Generated by Django 3.2.15 on 2022-12-08 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('robots', '0023_monthlyreturns'),
    ]

    operations = [
        migrations.CreateModel(
            name='Strategy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('type', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.RenameField(
            model_name='robots',
            old_name='strategy',
            new_name='strategy_id',
        ),
    ]
