# Generated by Django 3.2.15 on 2022-12-12 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('robots', '0024_auto_20221208_1909'),
    ]

    operations = [
        migrations.RenameField(
            model_name='robots',
            old_name='robot_code',
            new_name='color',
        ),
    ]
