# Generated by Django 3.2.15 on 2022-12-12 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('robots', '0025_rename_robot_code_robots_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='robots',
            name='color',
            field=models.CharField(default='#828282', max_length=20),
        ),
    ]
