# Generated by Django 4.1.5 on 2023-01-27 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('robots', '0026_alter_robots_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='strategy',
            name='description',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='strategy',
            name='type',
            field=models.CharField(max_length=50),
        ),
    ]
