# Generated by Django 4.1.5 on 2023-01-27 22:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('robots', '0027_strategy_description_alter_strategy_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='strategy',
            name='type',
        ),
    ]
