# Generated by Django 4.1.5 on 2023-01-30 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('robots', '0028_remove_strategy_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='robots',
            old_name='strategy_id',
            new_name='strategy',
        ),
    ]
