# Generated by Django 3.0.5 on 2020-10-17 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Instruments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instrument_name', models.CharField(default='', max_length=30)),
                ('instrument_type', models.CharField(default='', max_length=30)),
                ('source', models.CharField(default='', max_length=30)),
            ],
        ),
    ]
