# Generated by Django 3.0.5 on 2021-07-02 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instrument', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='instruments',
            name='inst_code',
            field=models.CharField(default='', max_length=30),
        ),
    ]
