# Generated by Django 3.0.5 on 2021-08-23 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instrument', '0002_instruments_inst_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inst_code', models.CharField(default='', max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='instruments',
            name='currency',
            field=models.CharField(default='', max_length=30),
        ),
    ]
