# Generated by Django 3.0.5 on 2021-08-23 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instrument', '0003_auto_20210823_2125'),
    ]

    operations = [
        migrations.AddField(
            model_name='prices',
            name='date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='prices',
            name='price',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='prices',
            name='source',
            field=models.CharField(default='', max_length=30),
        ),
    ]
