# Generated by Django 4.1.5 on 2023-02-20 21:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instrument', '0008_rename_source_instruments_country_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='instruments',
            old_name='inst_code',
            new_name='code',
        ),
        migrations.RenameField(
            model_name='instruments',
            old_name='instrument_name',
            new_name='group',
        ),
        migrations.RenameField(
            model_name='instruments',
            old_name='instrument_sub_type',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='instruments',
            old_name='instrument_type',
            new_name='type',
        ),
    ]
