# Generated by Django 4.1.5 on 2023-02-22 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instrument', '0009_rename_inst_code_instruments_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instruments',
            name='name',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
