# Generated by Django 4.1.5 on 2023-02-22 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instrument', '0010_alter_instruments_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='instruments',
            name='ticker',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='instruments',
            name='name',
            field=models.CharField(default='', max_length=30),
        ),
    ]
