# Generated by Django 4.1.5 on 2023-02-22 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instrument', '0011_instruments_ticker_alter_instruments_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tickers',
            name='internal_ticker',
        ),
    ]
