# Generated by Django 4.2 on 2023-04-28 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instrument', '0012_remove_tickers_internal_ticker'),
    ]

    operations = [
        migrations.AddField(
            model_name='tickers',
            name='margin',
            field=models.FloatField(default=0.0),
        ),
    ]
