# Generated by Django 4.2 on 2023-05-26 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instrument', '0015_remove_instruments_ticker'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prices',
            name='inst_code',
            field=models.IntegerField(default='', max_length=30),
        ),
    ]
