# Generated by Django 4.2 on 2023-08-08 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instrument', '0016_alter_prices_inst_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instruments',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
