# Generated by Django 3.2.7 on 2024-09-29 19:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('instrument', '0017_alter_instruments_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prices',
            name='inst_code',
        ),
        migrations.AddField(
            model_name='prices',
            name='instrument',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='instrument.instruments'),
        ),
    ]
