# Generated by Django 5.1.2 on 2025-03-06 21:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instrument', '0020_alter_instruments_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tickers',
            name='inst_code',
            field=models.ForeignKey(blank=True, db_column='inst_code', default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='instrument.instruments'),
        ),
    ]
