# Generated by Django 5.1.2 on 2025-03-21 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instrument', '0021_alter_tickers_inst_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='instruments',
            name='archive',
            field=models.BooleanField(default=False),
        ),
    ]
