# Generated by Django 5.1.2 on 2025-05-22 20:41

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instrument', '0022_instruments_archive'),
    ]

    operations = [
        migrations.AddField(
            model_name='prices',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
