# Generated by Django 3.2.7 on 2024-09-18 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cash',
            old_name='portfolio_name',
            new_name='portfolio_code',
        ),
        migrations.RenameField(
            model_name='margin',
            old_name='portfolio_name',
            new_name='portfolio_code',
        ),
        migrations.RenameField(
            model_name='positions',
            old_name='portfolio_name',
            new_name='portfolio_code',
        ),
        migrations.RenameField(
            model_name='ugl',
            old_name='portfolio_name',
            new_name='portfolio_code',
        ),
    ]
