# Generated by Django 3.0.5 on 2020-10-06 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CashFlow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('port_id', models.IntegerField(default=0)),
                ('amount', models.FloatField(default=0.0)),
                ('type', models.CharField(default='', max_length=30)),
            ],
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='portfolio_name',
            field=models.CharField(default='', max_length=30, unique=True),
        ),
    ]
