# Generated by Django 3.2.7 on 2024-09-18 18:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('instrument', '0017_alter_instruments_name'),
        ('portfolio', '0002_auto_20240918_2009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='positions',
            name='security',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instrument.instruments'),
        ),
    ]
