# Generated by Django 3.0.5 on 2020-10-06 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_auto_20201006_1031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashflow',
            name='portfolio_name',
            field=models.CharField(default='', max_length=30),
        ),
    ]
