# Generated by Django 3.2.7 on 2024-09-19 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_alter_positions_security'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='broker',
            field=models.CharField(default='', max_length=30),
        ),
    ]
