# Generated by Django 5.1.2 on 2025-03-10 09:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_rename_is_automated_portfolio_trading_allowed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='positions',
            name='security',
        ),
        migrations.RemoveField(
            model_name='positions',
            name='transaction',
        ),
        migrations.AddField(
            model_name='nav',
            name='portfolio',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='portfolio.portfolio'),
        ),
        migrations.DeleteModel(
            name='Margin',
        ),
        migrations.DeleteModel(
            name='Positions',
        ),
    ]
