# Generated by Django 3.2.7 on 2024-09-20 12:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_transaction_broker'),
    ]

    operations = [
        migrations.AddField(
            model_name='positions',
            name='transaction',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='portfolio.transaction'),
        ),
    ]
