# Generated by Django 3.0.5 on 2020-10-06 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_auto_20201006_1038'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashflow',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
