# Generated by Django 3.2.7 on 2024-09-22 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_positions_transaction'),
    ]

    operations = [
        migrations.RenameField(
            model_name='portgroup',
            old_name='type',
            new_name='children',
        ),
        migrations.RemoveField(
            model_name='portgroup',
            name='children_id',
        ),
        migrations.RemoveField(
            model_name='portgroup',
            name='connection_id',
        ),
        migrations.RemoveField(
            model_name='portgroup',
            name='level',
        ),
        migrations.AlterField(
            model_name='portgroup',
            name='parent_id',
            field=models.IntegerField(default=0),
        ),
    ]
