# Generated by Django 5.1.2 on 2025-03-10 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_remove_positions_security_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='portfolio_code',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
