# Generated by Django 3.2.7 on 2024-09-22 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_auto_20240922_0759'),
    ]

    operations = [
        migrations.RenameField(
            model_name='portgroup',
            old_name='children',
            new_name='name',
        ),
    ]
