# Generated by Django 3.0.5 on 2020-10-09 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_instruments_nav_trade'),
    ]

    operations = [
        migrations.AddField(
            model_name='trade',
            name='sec_type',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='trade',
            name='security',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='trade',
            name='source',
            field=models.CharField(default='', max_length=30),
        ),
    ]
