# Generated by Django 3.2.7 on 2024-09-22 11:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0007_rename_children_portgroup_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portgroup',
            name='name',
        ),
        migrations.AddField(
            model_name='portgroup',
            name='child',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='portfolio.portfolio'),
        ),
    ]
