# Generated by Django 5.1.2 on 2025-03-12 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0007_holding_portfolio_totalreturn_portfolio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='option',
        ),
        migrations.AddField(
            model_name='portfolio',
            name='multicurrency_allowed',
            field=models.BooleanField(default=False),
        ),
    ]
