# Generated by Django 3.2.7 on 2024-09-22 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0008_auto_20240922_1306'),
    ]

    operations = [
        migrations.AddField(
            model_name='portgroup',
            name='type',
            field=models.CharField(default='', max_length=30),
        ),
    ]
