# Generated by Django 5.1.2 on 2025-03-21 21:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instrument', '0022_instruments_archive'),
        ('portfolio', '0008_remove_transaction_option_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='security',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='instrument.instruments'),
        ),
    ]
