# Generated by Django 3.2.7 on 2024-09-22 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0009_portgroup_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portgroup',
            name='child',
        ),
        migrations.RemoveField(
            model_name='portgroup',
            name='type',
        ),
    ]
