# Generated by Django 3.0.5 on 2020-10-14 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0009_auto_20201014_2116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trade',
            name='security',
            field=models.IntegerField(default=0),
        ),
    ]
