# Generated by Django 5.1.2 on 2025-03-24 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0009_alter_transaction_security'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='securityreturn',
            name='contribution',
        ),
        migrations.RemoveField(
            model_name='securityreturn',
            name='fx_return',
        ),
        migrations.RemoveField(
            model_name='securityreturn',
            name='income_return',
        ),
        migrations.RemoveField(
            model_name='securityreturn',
            name='price_return',
        ),
        migrations.RemoveField(
            model_name='securityreturn',
            name='trade_return',
        ),
        migrations.AddField(
            model_name='holding',
            name='abs_weight',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='holding',
            name='fx_cont',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='holding',
            name='fx_pnl',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='holding',
            name='fx_return',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='holding',
            name='gross_weight',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='holding',
            name='inc_cont',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='holding',
            name='income_pnl',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='holding',
            name='income_return',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='holding',
            name='price_cont',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='holding',
            name='price_pnl',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='holding',
            name='price_return',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='holding',
            name='total_pnl',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='holding',
            name='total_return',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='holding',
            name='trade_return',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='holding',
            name='trd_cont',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='holding',
            name='trd_pnl',
            field=models.FloatField(default=0.0),
        ),
    ]
