# Generated by Django 3.0.5 on 2020-10-14 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0010_auto_20201014_2154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='positions',
            name='security',
            field=models.IntegerField(default=0),
        ),
    ]
