# Generated by Django 5.1.2 on 2025-03-25 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0010_remove_securityreturn_contribution_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='securityreturn',
            name='fx_cont',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='securityreturn',
            name='fx_pnl',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='securityreturn',
            name='fx_return',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='securityreturn',
            name='inc_cont',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='securityreturn',
            name='income_pnl',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='securityreturn',
            name='income_return',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='securityreturn',
            name='price_cont',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='securityreturn',
            name='price_pnl',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='securityreturn',
            name='price_return',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='securityreturn',
            name='total_pnl',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='securityreturn',
            name='total_return',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='securityreturn',
            name='trade_return',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='securityreturn',
            name='trd_cont',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='securityreturn',
            name='trd_pnl',
            field=models.FloatField(default=0.0),
        ),
    ]
