# Generated by Django 5.1.2 on 2025-03-26 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0011_securityreturn_fx_cont_securityreturn_fx_pnl_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='holding',
            name='beg_market_price',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='holding',
            name='beg_quantity',
            field=models.FloatField(default=0.0),
        ),
    ]
