# Generated by Django 3.2.7 on 2024-09-23 04:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0012_rename_child_portgroup_portfolio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portgroup',
            name='portfolio',
        ),
        migrations.AddField(
            model_name='portgroup',
            name='portfolio_code',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='portfolio.portfolio', to_field='portfolio_code'),
        ),
    ]
