# Generated by Django 3.2.7 on 2024-09-23 04:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0013_auto_20240923_0612'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portgroup',
            name='parent_id',
        ),
        migrations.RemoveField(
            model_name='portgroup',
            name='portfolio_code',
        ),
        migrations.AddField(
            model_name='portgroup',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='portfolio.portgroup'),
        ),
        migrations.AddField(
            model_name='portgroup',
            name='portfolio',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='portfolio.portfolio'),
        ),
    ]
