# Generated by Django 3.0.5 on 2020-10-17 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0013_auto_20201014_2234'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Instruments',
        ),
    ]
