# Generated by Django 5.1.2 on 2025-04-28 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0013_holding_beg_bv_holding_beg_mv'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='broker_id',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
