# Generated by Django 3.2.7 on 2024-09-23 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0014_auto_20240923_0633'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portgroup',
            name='parent',
        ),
        migrations.AddField(
            model_name='portgroup',
            name='parent_id',
            field=models.IntegerField(default=0),
        ),
    ]
