# Generated by Django 5.1.2 on 2025-05-20 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0014_alter_transaction_broker_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='allow_external_signals',
            field=models.BooleanField(default=False),
        ),
    ]
