# Generated by Django 3.0.5 on 2020-12-03 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0014_delete_instruments'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashflow',
            name='user',
            field=models.CharField(default='', max_length=30),
        ),
    ]
