# Generated by Django 3.0.5 on 2020-12-03 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0015_cashflow_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='currency',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='inception_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='status',
            field=models.CharField(default='', max_length=30),
        ),
    ]
