# Generated by Django 3.2.7 on 2024-09-25 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0015_auto_20240923_0644'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='open_status',
            field=models.CharField(default='Open', max_length=50),
        ),
    ]
