# Generated by Django 5.1.2 on 2025-05-20 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0015_portfolio_allow_external_signals'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='portfolio_code',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True),
        ),
    ]
