# Generated by Django 5.1.2 on 2025-05-23 09:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_brokeraccounts_broker'),
        ('portfolio', '0016_alter_portfolio_portfolio_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='holding',
            name='account',
            field=models.ForeignKey(blank=True, db_column='account_id', default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.brokeraccounts'),
        ),
    ]
