# Generated by Django 3.2.7 on 2024-09-27 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0016_alter_transaction_open_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='fx_pnl',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='local_pnl',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='realized_pnl',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='sec_group',
        ),
    ]
