# Generated by Django 3.2.7 on 2024-09-30 10:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('instrument', '0018_auto_20240929_2139'),
        ('portfolio', '0017_auto_20240927_1241'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='holding',
            name='data',
        ),
        migrations.AddField(
            model_name='holding',
            name='beg_bv',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='holding',
            name='beg_mv',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='holding',
            name='beg_quantity',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='holding',
            name='end_bv',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='holding',
            name='end_mv',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='holding',
            name='end_quantity',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='holding',
            name='fx_rate',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='holding',
            name='instrument',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='instrument.instruments'),
        ),
        migrations.AddField(
            model_name='holding',
            name='price',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='holding',
            name='weight',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='holding',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
