# Generated by Django 3.0.5 on 2020-12-03 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0017_auto_20201203_2005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nav',
            name='date',
            field=models.DateField(auto_now=True),
        ),
    ]
