# Generated by Django 3.2.7 on 2024-10-01 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0018_auto_20240930_1251'),
    ]

    operations = [
        migrations.RenameField(
            model_name='holding',
            old_name='beg_bv',
            new_name='bv',
        ),
        migrations.RenameField(
            model_name='holding',
            old_name='beg_mv',
            new_name='market_price',
        ),
        migrations.RenameField(
            model_name='holding',
            old_name='beg_quantity',
            new_name='mv',
        ),
        migrations.RenameField(
            model_name='holding',
            old_name='end_bv',
            new_name='quantity',
        ),
        migrations.RenameField(
            model_name='holding',
            old_name='end_mv',
            new_name='rgl',
        ),
        migrations.RenameField(
            model_name='holding',
            old_name='end_quantity',
            new_name='trade_price',
        ),
        migrations.RenameField(
            model_name='holding',
            old_name='price',
            new_name='ugl',
        ),
        migrations.AddField(
            model_name='holding',
            name='inv_num',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='holding',
            name='trade_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='holding',
            name='trd_num',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='holding',
            name='date',
            field=models.DateField(null=True),
        ),
    ]
