# Generated by Django 3.2.7 on 2024-10-01 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0019_auto_20241001_1134'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transactionpnl',
            name='closing_date',
        ),
        migrations.AddField(
            model_name='transactionpnl',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='cash',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='margin',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='ugl',
            name='date',
            field=models.DateField(null=True),
        ),
    ]
