# Generated by Django 3.0.5 on 2020-12-03 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0019_auto_20201203_2011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='inception_date',
            field=models.DateField(auto_now=True),
        ),
    ]
