# Generated by Django 3.0.5 on 2021-01-26 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0020_auto_20201203_2033'),
    ]

    operations = [
        migrations.CreateModel(
            name='PortGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parent_id', models.IntegerField()),
                ('children_id', models.IntegerField()),
            ],
        ),
    ]
