# Generated by Django 3.2.7 on 2024-10-01 19:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0020_auto_20241001_1209'),
    ]

    operations = [
        migrations.CreateModel(
            name='RGL',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('portfolio_code', models.CharField(default='', max_length=30)),
                ('base_mv', models.FloatField(default=0.0)),
                ('local_mv', models.FloatField(default=0.0)),
                ('date', models.DateField(null=True)),
                ('transaction', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='portfolio.transaction')),
            ],
        ),
    ]
