# Generated by Django 3.2.7 on 2024-10-02 12:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0021_rgl'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='holding',
            name='trd_num',
        ),
        migrations.AddField(
            model_name='holding',
            name='trd',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='portfolio.transaction'),
        ),
    ]
