# Generated by Django 3.0.5 on 2021-07-02 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0022_portgroup_connection_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='portfolio_name',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
