# Generated by Django 3.2.7 on 2024-10-03 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0022_auto_20241002_1428'),
    ]

    operations = [
        migrations.AddField(
            model_name='holding',
            name='margin_rate',
            field=models.FloatField(default=0.0),
        ),
    ]
