# Generated by Django 3.2.7 on 2024-10-04 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0023_holding_margin_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='holding',
            name='trade_type',
            field=models.CharField(default='', max_length=30),
        ),
    ]
