# Generated by Django 3.0.5 on 2021-07-02 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0023_auto_20210702_2059'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='portfolio_code',
            field=models.CharField(default='', max_length=30),
        ),
    ]
