# Generated by Django 3.0.5 on 2021-07-02 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0024_portfolio_portfolio_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='portfolio_code',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='portfolio_name',
            field=models.CharField(default='', max_length=30),
        ),
    ]
