# Generated by Django 3.0.5 on 2021-07-02 22:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0025_auto_20210703_0000'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cashflow',
            old_name='portfolio_name',
            new_name='portfolio_code',
        ),
    ]
