# Generated by Django 3.0.5 on 2021-07-06 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0026_auto_20210703_0018'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashflow',
            name='currency',
            field=models.CharField(default='', max_length=30),
        ),
    ]
