# Generated by Django 3.0.5 on 2021-07-09 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0028_cashholding'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashholding',
            name='date',
            field=models.DateField(),
        ),
    ]
