# Generated by Django 3.2.7 on 2022-07-30 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0031_nav_portfolio_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nav',
            name='date',
            field=models.DateField(),
        ),
    ]
