# Generated by Django 3.2.7 on 2022-07-30 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0032_alter_nav_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='trade',
            name='currency',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='trade',
            name='trading_cost',
            field=models.FloatField(default=0.0),
        ),
    ]
