# Generated by Django 3.2.7 on 2022-07-30 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0033_auto_20220730_1303'),
    ]

    operations = [
        migrations.AddField(
            model_name='trade',
            name='transaction_type',
            field=models.CharField(default='', max_length=30),
        ),
    ]
