# Generated by Django 3.2.7 on 2022-08-18 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0034_trade_transaction_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trade',
            old_name='portfolio_name',
            new_name='portfolio_code',
        ),
    ]
