# Generated by Django 3.2.7 on 2022-08-18 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0035_rename_portfolio_name_trade_portfolio_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trade',
            name='currency',
        ),
    ]
