# Generated by Django 3.2.7 on 2022-08-18 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0037_remove_trade_sec_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trade',
            name='source',
        ),
    ]
