# Generated by Django 3.2.7 on 2022-08-18 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0038_remove_trade_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='trade',
            name='transaction_link_code',
            field=models.CharField(default='', max_length=50),
        ),
    ]
