# Generated by Django 3.2.15 on 2022-09-14 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0040_alter_trade_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='inception_date',
            field=models.DateField(),
        ),
    ]
