# Generated by Django 4.1.5 on 2023-04-05 16:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0043_robots_portfolio_is_automated_portfolio_manager_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='creation_date',
            field=models.DateField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='is_terminated',
            field=models.CharField(default=False, max_length=30),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='termination_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='inception_date',
            field=models.DateField(null=True),
        ),
    ]
