# Generated by Django 4.2 on 2023-04-12 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0044_portfolio_creation_date_portfolio_is_terminated_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('portfolio_code', models.CharField(default='', max_length=30)),
                ('security_id', models.IntegerField(default=0)),
                ('quantity', models.FloatField(default=0.0)),
                ('price', models.FloatField(default=0.0)),
                ('mv', models.FloatField(default=0.0)),
                ('date', models.DateField()),
                ('currency', models.CharField(default='', max_length=30)),
                ('trading_cost', models.FloatField(default=0.0)),
                ('transaction_type', models.CharField(default='', max_length=30)),
                ('transaction_link_code', models.CharField(default='', max_length=50)),
            ],
        ),
    ]
