# Generated by Django 4.2 on 2023-04-17 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0049_remove_transaction_security_id_transaction_security'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='sub_type',
            field=models.CharField(default='', max_length=30),
        ),
    ]
