# Generated by Django 4.2 on 2023-04-20 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0050_transaction_sub_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='trade_date',
            field=models.DateField(null=True),
        ),
    ]
