# Generated by Django 4.2 on 2023-04-20 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0051_alter_transaction_trade_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='sec_group',
            field=models.CharField(default='', max_length=30),
        ),
    ]
