# Generated by Django 4.2 on 2023-04-20 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0052_transaction_sec_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='is_open',
            field=models.CharField(default='Open', max_length=50),
        ),
    ]
