# Generated by Django 4.2 on 2023-04-20 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0053_transaction_is_open'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='is_open',
            field=models.CharField(default='', max_length=50),
        ),
    ]
