# Generated by Django 4.2 on 2023-04-20 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0054_alter_transaction_is_open'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='sub_type',
        ),
    ]
