# Generated by Django 4.2 on 2023-04-20 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0055_remove_transaction_sub_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='is_open',
            new_name='open_status',
        ),
    ]
