# Generated by Django 4.2 on 2023-04-24 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0056_rename_is_open_transaction_open_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='broker',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='transaction',
            name='broker_id',
            field=models.IntegerField(null=True),
        ),
    ]
