# Generated by Django 4.2 on 2023-04-26 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0057_transaction_broker_transaction_broker_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='broker',
        ),
        migrations.AddField(
            model_name='transaction',
            name='account_id',
            field=models.IntegerField(null=True),
        ),
    ]
