# Generated by Django 4.2 on 2023-04-27 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0058_remove_transaction_broker_transaction_account_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='margin',
            field=models.FloatField(default=0.0),
        ),
    ]
