# Generated by Django 4.2 on 2023-05-04 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0059_transaction_margin'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionPnl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.IntegerField(default=0)),
                ('portfolio_code', models.CharField(default='', max_length=30)),
                ('security', models.IntegerField(default=0)),
                ('pnl', models.FloatField(default=0.0)),
                ('closing_date', models.DateField()),
            ],
        ),
        migrations.AlterField(
            model_name='positions',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
