# Generated by Django 4.2 on 2023-05-04 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0060_transactionpnl_alter_positions_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactionpnl',
            name='closing_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
