# Generated by Django 4.2 on 2023-05-12 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0061_alter_transactionpnl_closing_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='margin_balance',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='transaction',
            name='net_flow',
            field=models.FloatField(default=0.0),
        ),
    ]
