# Generated by Django 4.2 on 2023-05-12 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0062_transaction_margin_balance_transaction_net_flow'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='net_flow',
            new_name='net_cashflow',
        ),
    ]
