# Generated by Django 4.2 on 2023-05-12 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0063_rename_net_flow_transaction_net_cashflow'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='outstanding_units',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='transaction',
            name='realized_pnl',
            field=models.FloatField(default=0.0),
        ),
    ]
