# Generated by Django 4.2 on 2023-05-13 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0064_transaction_outstanding_units_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='outstanding_units',
        ),
    ]
