# Generated by Django 4.2 on 2023-05-13 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0065_remove_transaction_outstanding_units'),
    ]

    operations = [
        migrations.CreateModel(
            name='Holding',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('portfolio_code', models.CharField(max_length=30)),
                ('security', models.IntegerField(default=0)),
                ('beginning_mv', models.FloatField(default=0.0)),
                ('units', models.FloatField(default=0.0)),
                ('price', models.FloatField(default=0.0)),
                ('ending_mv', models.FloatField(default=0.0)),
                ('weight', models.FloatField(default=0.0)),
            ],
        ),
        migrations.DeleteModel(
            name='PortfolioHoldings',
        ),
    ]
