# Generated by Django 4.2 on 2023-05-13 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0066_holding_delete_portfolioholdings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='security',
            field=models.IntegerField(default=0),
        ),
    ]
