# Generated by Django 4.2 on 2023-05-13 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0067_alter_transaction_security'),
    ]

    operations = [
        migrations.AddField(
            model_name='holding',
            name='data',
            field=models.JSONField(null=True),
        ),
    ]
