# Generated by Django 4.2 on 2023-05-13 21:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0068_holding_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='holding',
            name='beginning_mv',
        ),
        migrations.RemoveField(
            model_name='holding',
            name='ending_mv',
        ),
        migrations.RemoveField(
            model_name='holding',
            name='price',
        ),
        migrations.RemoveField(
            model_name='holding',
            name='security',
        ),
        migrations.RemoveField(
            model_name='holding',
            name='units',
        ),
        migrations.RemoveField(
            model_name='holding',
            name='weight',
        ),
    ]
