# Generated by Django 4.2 on 2023-05-17 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0069_remove_holding_beginning_mv_remove_holding_ending_mv_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nav',
            name='portfolio_name',
        ),
    ]
