# Generated by Django 4.2 on 2023-05-23 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0070_remove_nav_portfolio_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_link_code',
            field=models.IntegerField(null=True),
        ),
    ]
