# Generated by Django 4.2 on 2023-05-23 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0071_alter_transaction_transaction_link_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_link_code',
            field=models.IntegerField(default=0),
        ),
    ]
