# Generated by Django 4.2 on 2023-05-24 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0072_alter_transaction_transaction_link_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='status',
            field=models.CharField(default='Not Funded', max_length=30),
        ),
    ]
