# Generated by Django 4.2 on 2023-05-24 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0073_alter_portfolio_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='valuation_frequency',
            field=models.CharField(default='Daily', max_length=30),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='weekend_valuation',
            field=models.BooleanField(default=False),
        ),
    ]
