# Generated by Django 4.2 on 2023-06-01 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0074_portfolio_valuation_frequency_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='nav',
            name='period_return',
            field=models.FloatField(default=0.0),
        ),
    ]
