# Generated by Django 4.2 on 2023-07-19 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0075_nav_period_return'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='description',
            field=models.CharField(default='', max_length=2000),
        ),
    ]
