# Generated by Django 4.2 on 2023-07-20 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0076_portfolio_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='nav',
            name='pnl',
            field=models.FloatField(default=0.0),
        ),
    ]
