# Generated by Django 4.2 on 2023-08-08 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0077_nav_pnl'),
    ]

    operations = [
        migrations.CreateModel(
            name='Performance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('portfolio_code', models.CharField(default='', max_length=30)),
                ('one_month', models.FloatField(default=0.0)),
                ('date', models.DateField(auto_now=True)),
            ],
        ),
    ]
