# Generated by Django 4.2 on 2023-08-08 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0078_performance'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='calc_holding',
            field=models.BooleanField(default=False),
        ),
    ]
