# Generated by Django 4.2 on 2023-08-08 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0079_portfolio_calc_holding'),
    ]

    operations = [
        migrations.AddField(
            model_name='nav',
            name='holding_nav',
            field=models.FloatField(default=0.0),
        ),
    ]
