# Generated by Django 4.2 on 2023-09-29 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0080_nav_holding_nav'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='option',
            field=models.CharField(default='', max_length=30),
        ),
    ]
