# Generated by Django 4.2 on 2023-10-03 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0081_transaction_option'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='financing_cost',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='transaction',
            name='local_cashflow',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='transaction',
            name='local_mv',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='transaction',
            name='local_pnl',
            field=models.FloatField(default=0.0),
        ),
    ]
