# Generated by Django 4.2 on 2023-10-03 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0082_transaction_financing_cost_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='fx_pnl',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='transaction',
            name='fx_rate',
            field=models.FloatField(default=0.0),
        ),
    ]
