# Generated by Django 4.2 on 2023-10-04 12:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0083_transaction_fx_pnl_transaction_fx_rate'),
    ]

    operations = [
        migrations.CreateModel(
            name='TotalReturn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_return', models.FloatField(default=0.0)),
                ('end_date', models.DateField(null=True)),
                ('period', models.CharField(default='', max_length=30)),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolio.portfolio')),
            ],
        ),
    ]
