# Generated by Django 4.2 on 2023-10-04 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0084_totalreturn'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='totalreturn',
            name='portfolio',
        ),
        migrations.AddField(
            model_name='totalreturn',
            name='portfolio_code',
            field=models.CharField(default='', max_length=30),
        ),
    ]
