# Generated by Django 4.2 on 2023-10-04 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0085_remove_totalreturn_portfolio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='perf_start_date',
            field=models.DateField(null=True),
        ),
    ]
