# Generated by Django 4.2 on 2023-10-08 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0086_portfolio_perf_start_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CashFlow',
        ),
        migrations.DeleteModel(
            name='CashHolding',
        ),
        migrations.DeleteModel(
            name='Performance',
        ),
        migrations.DeleteModel(
            name='Trade',
        ),
        migrations.AlterField(
            model_name='transaction',
            name='fx_rate',
            field=models.FloatField(default=1.0),
        ),
    ]
