# Generated by Django 4.2 on 2023-10-08 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0087_delete_cashflow_delete_cashholding_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='robots',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
