# Generated by Django 4.2 on 2023-10-08 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0088_robots_is_active'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Robots',
            new_name='TradeRoutes',
        ),
    ]
