# Generated by Django 4.2 on 2023-10-08 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0089_rename_robots_traderoutes'),
    ]

    operations = [
        migrations.AddField(
            model_name='traderoutes',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
    ]
