# Generated by Django 3.2.7 on 2023-10-13 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0090_traderoutes_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='nav',
            name='unrealized_pnl',
            field=models.FloatField(default=0.0),
        ),
    ]
