# Generated by Django 3.2.7 on 2023-10-19 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0091_nav_unrealized_pnl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='traderoutes',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
