# Generated by Django 3.2.7 on 2023-12-05 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0092_alter_traderoutes_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='pricing_tolerance',
            field=models.IntegerField(default=30),
        ),
    ]
