# Generated by Django 3.2.7 on 2024-02-21 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0093_portfolio_pricing_tolerance'),
    ]

    operations = [
        migrations.AddField(
            model_name='nav',
            name='cost',
            field=models.FloatField(default=0.0),
        ),
    ]
