# Generated by Django 3.2.7 on 2024-05-05 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0094_nav_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='nav',
            name='redemption',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='nav',
            name='subscription',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='nav',
            name='total_cf',
            field=models.FloatField(default=0.0),
        ),
    ]
