# Generated by Django 3.2.7 on 2024-05-05 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0095_auto_20240505_2236'),
    ]

    operations = [
        migrations.AddField(
            model_name='nav',
            name='dietz_return',
            field=models.FloatField(default=0.0),
        ),
    ]
