# Generated by Django 3.2.7 on 2024-05-06 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0096_nav_dietz_return'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nav',
            old_name='dietz_return',
            new_name='price_return',
        ),
        migrations.RenameField(
            model_name='nav',
            old_name='period_return',
            new_name='trade_return',
        ),
        migrations.AddField(
            model_name='nav',
            name='ugl_diff',
            field=models.FloatField(default=0.0),
        ),
    ]
