# Generated by Django 3.2.7 on 2024-05-06 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0097_auto_20240506_1036'),
    ]

    operations = [
        migrations.AddField(
            model_name='nav',
            name='total_pnl',
            field=models.FloatField(default=0.0),
        ),
    ]
