# Generated by Django 3.2.7 on 2024-05-07 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0098_nav_total_pnl'),
    ]

    operations = [
        migrations.CreateModel(
            name='SecurityReturn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('portfolio_code', models.CharField(default='', max_length=30)),
                ('date', models.DateField()),
                ('security', models.IntegerField(default=0)),
                ('weight', models.FloatField(default=0.0)),
                ('trade_return', models.FloatField(default=0.0)),
                ('price_return', models.FloatField(default=0.0)),
                ('income_return', models.FloatField(default=0.0)),
                ('fx_return', models.FloatField(default=0.0)),
                ('contribution', models.FloatField(default=0.0)),
            ],
        ),
    ]
