# Generated by Django 4.2 on 2023-05-02 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notifications',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('portfolio_code', models.CharField(default='', max_length=50)),
                ('message', models.CharField(default='', max_length=50)),
                ('sub_message', models.CharField(default='', max_length=50)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
