# Generated by Django 4.2 on 2023-05-02 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notifications',
            name='broker_name',
            field=models.CharField(default='', max_length=50),
        ),
    ]
