# Generated by Django 3.2.7 on 2023-12-20 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade_app', '0002_notifications_broker_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notifications',
            name='created_on',
        ),
        migrations.AddField(
            model_name='notifications',
            name='date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='notifications',
            name='security',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='notifications',
            name='time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
