# Generated by Django 5.1.2 on 2025-04-30 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade_app', '0004_orders'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notifications',
            name='message',
            field=models.CharField(default='', max_length=500),
        ),
    ]
