# Generated by Django 5.1.2 on 2025-05-19 16:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0014_alter_transaction_broker_id'),
        ('trade_app', '0006_signal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='signal',
            name='portfolio_code',
        ),
        migrations.AddField(
            model_name='signal',
            name='portfolio',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='signals', to='portfolio.portfolio'),
        ),
    ]
