# Generated by Django 5.1.2 on 2025-05-19 20:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_brokeraccounts_broker'),
        ('portfolio', '0014_alter_transaction_broker_id'),
        ('trade_app', '0007_remove_signal_portfolio_code_signal_portfolio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('security_id', models.IntegerField()),
                ('symbol', models.CharField(max_length=50)),
                ('side', models.CharField(choices=[('BUY', 'Buy'), ('SELL', 'Sell')], max_length=4)),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=20)),
                ('executed_price', models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True)),
                ('fx_rate', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('broker_order_id', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('EXECUTED', 'Executed'), ('REJECTED', 'Rejected'), ('FAILED', 'Failed'), ('PARTIAL', 'Partial')], default='PENDING', max_length=20)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('executed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('broker_account', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='accounts.brokeraccounts')),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolio.portfolio')),
                ('signal', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='trade_app.signal')),
            ],
        ),
        migrations.DeleteModel(
            name='Orders',
        ),
    ]
