# Generated by Django 5.1.2 on 2025-05-20 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade_app', '0008_order_delete_orders'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='signal',
            name='account_id',
        ),
        migrations.RemoveField(
            model_name='signal',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='signal',
            name='security_id',
        ),
        migrations.RemoveField(
            model_name='signal',
            name='transaction_type',
        ),
        migrations.AddField(
            model_name='signal',
            name='source',
            field=models.CharField(choices=[('INTERNAL', 'Internal'), ('EXTERNAL', 'External')], default='INTERNAL', max_length=10),
        ),
    ]
