# Generated by Django 5.1.2 on 2025-05-20 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade_app', '0009_remove_signal_account_id_remove_signal_quantity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='signal',
            name='type',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('EXECUTED', 'Executed'), ('FAILED', 'Failed')], default='OPEN', max_length=20),
        ),
    ]
