# Generated by Django 5.1.2 on 2025-05-21 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade_app', '0010_signal_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signal',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('EXECUTED', 'Executed'), ('FAILED', 'Failed'), ('REJECTED', 'Rejected'), ('PARTIALLY EXECUTED', 'Partially Executed')], default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='signal',
            name='type',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('EXECUTED', 'Executed'), ('FAILED', 'Failed'), ('REJECTED', 'Rejected'), ('PARTIALLY EXECUTED', 'Partially Executed')], default='OPEN', max_length=20),
        ),
    ]
